### ISSUE TITLE
Conda missing NAME files

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest#433]
- Include `*txt` for tutorial

**Comment by andrewgryan** [comment]
Traceback from a fresh conda environment

```
making: ./NAME
copying: /Users/andrewryan/opt/miniconda3/envs/forest-dev/lib/python3.7/site-packages/forest/tutorial/NAME/Fields_grid1_C1_T1_200810080100.txt to ./NAME/Fields_grid1_C1_T1_200810080100.txt
Traceback (most recent call last):
  File "/Users/andrewryan/opt/miniconda3/envs/forest-dev/bin/forest-tutorial", line 8, in <module>
    sys.exit(main())
  File "/Users/andrewryan/opt/miniconda3/envs/forest-dev/lib/python3.7/site-packages/forest/tutorial/main.py", line 32, in main
    core.build_all(build_dir=args.build_dir)
  File "/Users/andrewryan/opt/miniconda3/envs/forest-dev/lib/python3.7/site-packages/forest/tutorial/core.py", line 59, in build_all
    build_file(build_dir, file_name)
  File "/Users/andrewryan/opt/miniconda3/envs/forest-dev/lib/python3.7/site-packages/forest/tutorial/core.py", line 92, in build_file
    shutil.copy2(src, dst)
  File "/Users/andrewryan/opt/miniconda3/envs/forest-dev/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/andrewryan/opt/miniconda3/envs/forest-dev/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/andrewryan/opt/miniconda3/envs/forest-dev/lib/python3.7/site-packages/forest/tutorial/NAME/Fields_grid1_C1_T1_200810080100.txt'

```
