### ISSUE TITLE
Yaml, where for art thou Yaml???

### ISSUE THREAD

**Issue by kaedonkers** [MetOffice/forest#438]
After conda installing a yaml, we can't find our yaml:
```bash
Traceback (most recent call last):
  File "/Users/kevin.donkers/opt/miniconda3/envs/forestmaster/bin/forest-tutorial", line 5, in <module>
    from forest.tutorial.main import main
  File "/Users/kevin.donkers/opt/miniconda3/envs/forestmaster/lib/python3.7/site-packages/forest/__init__.py", line 33, in <module>
    from .config import *
  File "/Users/kevin.donkers/opt/miniconda3/envs/forestmaster/lib/python3.7/site-packages/forest/config.py", line 25, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by kaedonkers** [comment]
Do we need to install pyyaml instead?

**Comment by kaedonkers** [comment]
Solved by conda installing `pyyaml`
